name: app_pasos_frontend
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  cupertino_icons: ^1.0.8
  dio: ^5.4.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  firebase_core: ^3.0.0
  firebase_messaging: ^15.0.0
  equatable: ^2.0.5
  fl_chart: ^0.68.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_dotenv: ^5.1.0
  flutter_secure_storage: ^9.0.0
  get_it: ^7.6.7
  go_router: ^14.0.0
  health: ^10.2.0
  logger: ^2.0.2+1
  web_socket_channel: ^2.4.0
  workmanager: ^0.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true

  assets:
    - .env
